name: feature build & deploy

on:
  pull_request:
    types: [closed]

concurrency:
  group: "feature-close"
  cancel-in-progress: false

env:
  ENV_NAME: ${{ github.ref/\//- }}

jobs:
  build:
    environment:
      name: ${{ env.ENV_NAME }}
      url: https://${{ env.ENV_NAME }}-domigmail-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
