name: feature closed

on:
  pull_request:
    types: [closed]

concurrency:
  group: "feature-close"
  cancel-in-progress: false

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      ENV_NAME: ${{ steps.genEnvName.outputs.ENV_NAME }}
    steps:
      - id: genEnvName
        name: set env
        run: echo "ENV_NAME=${{ github.event.pull_request.head.ref }}" | tr / - >> $GITHUB_OUTPUT

  cleanup:
    needs: [set-vars]
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.set-vars.outputs.ENV_NAME }}
      url: https://${{ needs.set-vars.outputs.ENV_NAME }}-deployme-domigmail-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login into openshift
        uses: ./.github/actions/oc-login
        with:
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: deploy pr
        working-directory: deploy/deployme
        run: helm uninstall ${{ needs.set-vars.outputs.ENV_NAME }}
