name: main build & deploy

on:
  push:
    branches: ["main"]

concurrency:
  group: "main"
  cancel-in-progress: true

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: npm install
        run: npm ci

      - name: npm build
        run: npm run build

      - name: docker build
        run: docker build . --file Dockerfile --tag ghcr.io/domirs/deployme:main

      - name: Push to registry
        run: docker push ghcr.io/domirs/deployme:main
