name: main build & deploy

on:
  push:
    branches: ["main"]

concurrency:
  group: "main"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: main
      url: https://main-domigmail-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: npm install
        run: npm ci

      - name: npm build
        run: npm run build


#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME}}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: deployme:${{github.ref_name}}
          
#      - name: docker build
#        run: docker build . --file Dockerfile --tag deployme:main

      - name: Login into openshift
        uses: ./.github/actions/oc-login

