name: Pull-Request Build

env:
  TZ: "Europe/Zurich"

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login into openshift
        uses: ./.github/actions/oc-login
